#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Composer.AndroidUI.Resource", IsApplication=true)]

namespace Composer.AndroidUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F010000
			public const int buttonPlay = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int buttonRecord = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int buttonStop = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int linearLayoutActions = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int linearLayoutMain = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int linearLayoutTracks = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int scrollViewTracks = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int textViewStatus = 2130771975;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
